### PR TITLE
Fix cursor_info_.pointer dangling pointer on device disconnect (wayland)

### LINKED ISSUE #436: Disconnecting mouse on wayland client results in Segmentation fault
Hi, I got the error "Segmentation fault", after disconnecting the mouse;

Flutter 3.27.1 • channel [user-branch] • unknown source
Framework • revision 17025dd882 (5 个月前) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2

and the same error with 3.24.2

Image

I checked the source code and found that the root cause is in lines 1523 to 1525. Based on the commit history, it might have been accidentally deleted, but I'm not sure.

Image

could please look into this issue, many thanks;

### PR DESCRIPTION
**Pull request by fredrikbmx**
First of all, thank you for taking the initiative to create a public fork of the flutter-elinux project.

Fixes https://github.com/sony/flutter-embedded-linux/issues/436. The issue was originally fixed in https://github.com/sony/flutter-embedded-linux/issues/403, but seems to have been reintroduced.

Prevents crashes by clearing cursor_info_.pointer when the pointer device (e.g., a mouse) disconnects and adding null check in UpdateFlutterCursor.

Changes:

- Clear cursor_info_.pointer when WL_SEAT_CAPABILITY_POINTER is removed
- Add null check in UpdateFlutterCursor before accessing pointer

### CODE REVIEW

File: AUTHORS [hunk 1]
```diff
@@ -22,3 +22,4 @@ Frede Emil Hoey Braendstrup <frederikbraendstrup@gmail.com>
 Dominique Martinet <dominique.martinet@atmark-techno.com>
 Wang Bin <wbsecg1@gmail.com>
 Jón Bjarni Bjarnason <jon@centroid.is>
+Fredrik Magnussen <fredrik.magnussen@biomerieux.com>
```
Comment (martinetd) [inline AUTHORS]: (nitpick) normally add new lines at end of file

File: src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc [hunk 2]
```diff
@@ -299,7 +299,13 @@ const wl_seat_listener ELinuxWindowWayland::kWlSeatListener = {
       if ((caps & WL_SEAT_CAPABILITY_POINTER) && !inputs.pointer) {
         inputs.pointer = wl_seat_get_pointer(seat);
         wl_pointer_add_listener(inputs.pointer, &kWlPointerListener, self);
+        ELINUX_LOG(TRACE) << "Pointer device connected: " << inputs.pointer;
       } else if (!(caps & WL_SEAT_CAPABILITY_POINTER) && inputs.pointer) {
+        ELINUX_LOG(TRACE) << "Pointer device disconnecting: " << inputs.pointer;
+        if (self->cursor_info_.pointer == inputs.pointer) {
```
Comment (martinetd) [inline src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc:305]: I wouldn't bother with this check and trace: just always clear it.

We only ever get a single `pointer` proxy from wayland (both for inputs.pointer and setup as listener), so self->cursor_info_.pointer if set with the wl_pointer argument is always this pointer, and nothing else would work remotely decently otherwise. (and if it's not set, setting null again is noop so won't hurt)

**Review by martinetd — COMMENTED** [review]
Nitpicks aside, I could reproduce and the "problem" is that UpdateFlutterCursor() can be called from the mouse cursor plugin without a pointer event, so it's more of a design problem in my opinion, but this clearing of the pointer + check below looks enough to me -- thanks a lot for the PR!

File: src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc (hunk 2 above)
Comment (martinetd) [reply src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc:305]: Ah, sorry, that's not true if there are multiple seats. that check is correct, ignore me.

Please add `Fixes: 434d509ffefd ("Multiple seats (#417)")` to your commit message though to tracking the regression

File: AUTHORS (hunk 1 above)
Comment (fredrikbmx) [reply AUTHORS]: Oops. I have added a newline at the end of the file.

File: src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc (hunk 2 above)
Comment (fredrikbmx) [reply src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc:305]: I rebased my commits and added `Fixes: 434d509ffefd ("Multiple seats (#417)")` to the end of the commit message.

**Comment by fredrikbmx** [comment]
> Nitpicks aside, I could reproduce and the "problem" is that UpdateFlutterCursor() can be called from the mouse cursor plugin without a pointer event, so it's more of a design problem in my opinion, but this clearing of the pointer + check below looks enough to me -- thanks a lot for the PR!

Thanks for the swift review!

File: src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc [hunk 3]
```diff
@@ -299,7 +299,13 @@ const wl_seat_listener ELinuxWindowWayland::kWlSeatListener = {
...
+          ELINUX_LOG(TRACE) << "Clearing cursor_info_.pointer to prevent dangling pointer";
```
Comment (lhoward) [inline src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc]: I think a trace log for clearing a dangling pointer is superfluous (apart from testing). I would remove this line.

File: src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc [hunk 4]
```diff
@@ -1526,6 +1532,10 @@ void ELinuxWindowWayland::UpdateVirtualKeyboardStatus(
 
 void ELinuxWindowWayland::UpdateFlutterCursor(const std::string& cursor_name) {
   if (view_properties_.use_mouse_cursor) {
+    if (!cursor_info_.pointer) {
+      ELINUX_LOG(TRACE) << "UpdateFlutterCursor called but pointer is null (device disconnected)";
```
Comment (lhoward) [inline src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc]: Ditto.

File: src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc (hunk 3 above)
Comment (fredrikbmx) [reply src/flutter/shell/platform/linux_embedded/window/elinux_window_wayland.cc]: Agree, removed

**Review by lhoward — APPROVED** [review]

**Comment by martinetd** [comment]
Thank you!
